# Generated by Django 5.1.6 on 2025-02-22 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "SET FOREIGN_KEY_CHECKS=0;",
            reverse_sql="SET FOREIGN_KEY_CHECKS=1;",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_product CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_localproject CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_localsprint CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_localversion CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_localrequirement CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_processeddata CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_iteration CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_version CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_requirement CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_removedrequirement CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "SET FOREIGN_KEY_CHECKS=1;",
            reverse_sql="SET FOREIGN_KEY_CHECKS=0;",
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('description', models.TextField(blank=True, verbose_name='产品描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='LocalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=100, unique=True, verbose_name='项目代码')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('sub_department', models.CharField(blank=True, max_length=100, null=True, verbose_name='子部门')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '本地项目',
                'verbose_name_plural': '本地项目',
                'indexes': [models.Index(fields=['project_code'], name='products_lo_project_0f03e7_idx'), models.Index(fields=['department', 'sub_department'], name='products_lo_departm_9798fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocalSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=100, verbose_name='迭代名称')),
                ('sprint_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='迭代编号')),
                ('status', models.CharField(max_length=50, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('actual_release_date', models.DateTimeField(blank=True, null=True, verbose_name='实际发布时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_user', models.CharField(max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='products.localproject')),
            ],
            options={
                'verbose_name': '本地迭代',
                'verbose_name_plural': '本地迭代',
            },
        ),
        migrations.CreateModel(
            name='LocalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100, verbose_name='版本名称')),
                ('release_type', models.CharField(max_length=20, verbose_name='发布类型')),
                ('status', models.CharField(max_length=50, verbose_name='状态')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('actual_release_date', models.DateTimeField(blank=True, null=True, verbose_name='实际发布时间')),
                ('created_user', models.CharField(max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='products.localproject')),
            ],
            options={
                'verbose_name': '本地版本',
                'verbose_name_plural': '本地版本',
            },
        ),
        migrations.CreateModel(
            name='LocalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=100, unique=True, verbose_name='需求ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('number', models.CharField(max_length=100, verbose_name='编号')),
                ('priority', models.CharField(max_length=50, verbose_name='优先级')),
                ('priority_cn', models.CharField(max_length=50, verbose_name='优先级中文')),
                ('issue_type', models.CharField(max_length=50, verbose_name='类型')),
                ('status', models.CharField(max_length=50, verbose_name='状态')),
                ('status_cn', models.CharField(max_length=50, verbose_name='状态中文')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_user', models.CharField(max_length=100, verbose_name='创建人')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('previous_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='上一版本')),
                ('current_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='当前版本')),
                ('latest_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='最新版本')),
                ('original_sprint_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='原始迭代ID')),
                ('original_version_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='原始版本ID')),
                ('previous_sprint', models.CharField(blank=True, max_length=100, null=True, verbose_name='上一迭代')),
                ('current_sprint', models.CharField(blank=True, max_length=100, null=True, verbose_name='当前迭代')),
                ('latest_sprint', models.CharField(blank=True, max_length=100, null=True, verbose_name='最新迭代')),
                ('change_status', models.CharField(choices=[('在版本内', '在版本内'), ('在迭代内', '在迭代内'), ('在版本和迭代内', '在版本和迭代内'), ('移出版本', '移出版本'), ('移出迭代', '移出迭代'), ('切换版本', '切换版本'), ('切换迭代', '切换迭代'), ('无版本', '无版本')], default='在版本内', max_length=20, verbose_name='变更状态')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='products.localsprint')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='products.localversion')),
            ],
            options={
                'verbose_name': '本地需求',
                'verbose_name_plural': '本地需求',
            },
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(help_text='数据类型，如products, calendar_events等', max_length=50)),
                ('data', models.JSONField(help_text='预处理后的JSON数据')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
            ],
            options={
                'verbose_name': '预处理数据',
                'verbose_name_plural': '预处理数据',
                'indexes': [models.Index(fields=['data_type'], name='products_pr_data_ty_637656_idx')],
            },
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planning', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('description', models.TextField(blank=True, verbose_name='迭代描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='products.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '迭代',
                'verbose_name_plural': '迭代',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('iteration', '迭代'), ('version', '版本')], default='iteration', max_length=20, verbose_name='发布类型')),
                ('iteration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='迭代号')),
                ('version_number', models.CharField(max_length=50, verbose_name='版本号')),
                ('release_date', models.DateField(verbose_name='发布日期')),
                ('status', models.CharField(choices=[('规划中', '规划中'), ('开发中', '开发中'), ('测试中', '测试中'), ('已发布', '已发布')], default='规划中', max_length=20, verbose_name='状态')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='版本概述')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '版本',
                'verbose_name_plural': '版本',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=50, verbose_name='需求ID')),
                ('title', models.CharField(max_length=200, verbose_name='需求标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='需求描述')),
                ('priority', models.IntegerField(choices=[(1, 'P1'), (2, 'P2'), (3, 'P3')], default=2, verbose_name='优先级')),
                ('status', models.CharField(choices=[('待开发', '待开发'), ('开发中', '开发中'), ('开发完成', '开发完成')], default='待开发', max_length=20, verbose_name='状态')),
                ('is_key_feature', models.BooleanField(default=False, verbose_name='是否核心功能')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='products.version', verbose_name='版本')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求',
                'ordering': ['priority', 'status'],
            },
        ),
        migrations.CreateModel(
            name='RemovedRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=50, verbose_name='需求ID')),
                ('title', models.CharField(max_length=200, verbose_name='需求标题')),
                ('change_type', models.CharField(choices=[('移除', '移除'), ('推迟', '推迟'), ('变更', '变更')], max_length=20, verbose_name='变更类型')),
                ('change_reason', models.TextField(verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_requirements', to='products.version', verbose_name='版本')),
            ],
            options={
                'verbose_name': '移除/变更需求',
                'verbose_name_plural': '移除/变更需求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='localsprint',
            index=models.Index(fields=['sprint_name'], name='products_lo_sprint__3ec1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='localsprint',
            index=models.Index(fields=['status'], name='products_lo_status_217873_idx'),
        ),
        migrations.AddIndex(
            model_name='localversion',
            index=models.Index(fields=['release_date'], name='products_lo_release_f2adf6_idx'),
        ),
        migrations.AddIndex(
            model_name='localversion',
            index=models.Index(fields=['status'], name='products_lo_status_27884e_idx'),
        ),
        migrations.AddIndex(
            model_name='localrequirement',
            index=models.Index(fields=['issue_id'], name='products_lo_issue_i_d0e614_idx'),
        ),
        migrations.AddIndex(
            model_name='localrequirement',
            index=models.Index(fields=['status'], name='products_lo_status_eca4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='localrequirement',
            index=models.Index(fields=['change_status'], name='products_lo_change__d3cccb_idx'),
        ),
    ]
