# Generated by Django 4.2.9 on 2025-01-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='产品描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=50, verbose_name='版本号')),
                ('release_date', models.DateField(verbose_name='发布日期')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('developing', '开发中'), ('testing', '测试中'), ('released', '已发布')], default='planning', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='版本描述')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '版本',
                'verbose_name_plural': '版本',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='需求标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='需求描述')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='products.version', verbose_name='版本')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求',
                'ordering': ['-priority', 'status'],
            },
        ),
    ]
