# Generated by Django 3.2.24 on 2025-02-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250222_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localrequirement',
            name='change_status',
            field=models.CharField(choices=[('存在版本中', '存在版本中'), ('存在迭代中', '存在迭代中'), ('存在版本和迭代中', '存在版本和迭代中'), ('移出版本', '移出版本'), ('移出迭代', '移出迭代'), ('切换版本', '切换版本'), ('切换迭代', '切换迭代'), ('不在版本和迭代中', '不在版本和迭代中')], default='不在版本和迭代中', max_length=20, verbose_name='变更状态'),
        ),
        migrations.AlterField(
            model_name='localrequirement',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='products.localversion'),
        ),
    ]
