# Generated by Django 3.2.24 on 2025-02-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250222_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='localrequirement',
            name='created_user_display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人显示名'),
        ),
        migrations.AddField(
            model_name='localrequirement',
            name='created_user_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='创建人邮箱'),
        ),
    ]
