# Generated by Django 5.1.6 on 2025-02-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproducts', '0002_add_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('规划中', '规划中'), ('开发中', '开发中'), ('测试中', '测试中'), ('已发布', '已发布')], default='规划中', max_length=20, verbose_name='状态'),
        ),
    ]
