# Generated by Django 5.1.6 on 2025-02-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproducts', '0003_alter_version_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='iteration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='迭代号'),
        ),
        migrations.AddField(
            model_name='version',
            name='type',
            field=models.CharField(choices=[('iteration', '迭代'), ('version', '版本')], default='iteration', max_length=20, verbose_name='发布类型'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='priority',
            field=models.CharField(choices=[('高', '高'), ('中', '中'), ('低', '低')], default='中', max_length=20, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('待处理', '待处理'), ('进行中', '进行中'), ('已完成', '已完成')], default='待处理', max_length=20, verbose_name='状态'),
        ),
    ]
